// <auto-generated />
namespace Municipal.TrashCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedstreettoaddressclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedstreettoaddressclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201609141718321_added street to address class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
