// <auto-generated />
namespace Municipal.TrashCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbsetaddedkeyforcollection_calendar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbsetaddedkeyforcollection_calendar));
        
        string IMigrationMetadata.Id
        {
            get { return "201609131902595_dbset added key for collection_calendar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
