// <auto-generated />
namespace Municipal.TrashCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcurrentusertoresterduserinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcurrentusertoresterduserinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201609191251367_added current user to resterduserinfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
